### ISSUE TITLE
What are our vertical target levels?

### ISSUE THREAD

**Issue by jbusecke** [m2lines/ocean_emulators#17]
Does somebody have our current target vertical levels on hand? @adcroft @adam-subel ?

Am I correct that we wanted to start with the vertical levels of the OM4 simulation here: /scratch/as15415/Data/Emulation_Data/OM4_Horizontal_Regrid_Old.zarr ?

**Comment by adcroft** [comment]
We chose to use a different grid to reduce size and it has no relation to the normal diagnostic grid nor the model grid. This is the file for thicknesses: 
```
netcdf diag_z19 {
dimensions:
        nz = 19 ;
variables:
        double dz(nz) ;
                dz:long_name = "z coordinate level thickness" ;
                dz:units = "m" ;

// global attributes:
                :filename = "diag_z19.nc" ;
data:

 dz = 5, 10, 15, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600, 800, 
    1000, 1000, 1000 ;
}
```
which gives diagnostic level centers at
```
2.5
10
22.5
40
65
105
165
250
375
550
775
1050
1400
1850
2400
3100
4000
5000
6000
```

**Comment by jbusecke** [comment]
Awesome. Thanks @adcroft. 

I am using these bounds now: 
```
array([   0,    5,   15,   30,   50,   80,  130,  200,  300,  450,  650,
        900, 1200, 1600, 2100, 2700, 3500, 4500, 5500, 6500])
```

**Comment by jbusecke** [comment]
Closing this issue for now.
